"""Normalized output returned by executable ModelDriver adapters."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class GeneratedArtifact:
    """Provider-independent generated bytes and delivery metadata."""

    data: bytes
    ext: str
    mime: str
    transcript: str | None = None
    usage: dict[str, Any] | None = None

    def as_tuple(self) -> tuple[bytes, str, str, str | None]:
        """Return the legacy ``generation.generate_media`` result shape."""

        return self.data, self.ext, self.mime, self.transcript
