#!/bin/bash
# ─────────────────────────────────────────────────────
# Versa AGi — Sentinel
#
# ⛔ MANIFEST: Any file path changes MUST be reflected in
#    design/Versa AGi - System Design.md (Section IX)
#
# Reactive file watcher that detects local workspace
# changes and triggers the Lifeline immediately —
# reducing agent-to-agent latency from ~60s to ~2-3s.
#
# Uses inotifywait (inotify-tools) to watch:
#   - .agent/inbox/inbox.json   (MCP inbound messages)
#   - agent_memory.db           (SQLite: tasks, approvals)
#
# NOTE: outbox.json is NOT watched (race condition loses data).
#       CRON handles outbox sync every 60s.
#
# CRON Lifeline remains as heartbeat/fallback for:
#   - External inbound messages (VersaVoice API polling)
#   - Timed events (reminders, scheduled tasks)
#
# Usage:  ./sentinel.sh
# Service: systemctl start versa-agi-sentinel
# ─────────────────────────────────────────────────────

set -uo pipefail

# ─── Configuration ───────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIFELINE_SCRIPT="${SCRIPT_DIR}/lifeline.sh"
LOG_FILE="/var/log/versa-agi-sentinel.log"
DEBOUNCE_SECONDS=15

# Source INI-derived paths (generated by setup.sh)
PATHS_ENV="/etc/versa-agi/paths.env"
if [ -f "${PATHS_ENV}" ]; then
  source "${PATHS_ENV}"
fi

AGENTS_DB="${VERSA_AGENTS_DB:-/var/lib/versa-agi/registry.db}"
LIFELINE_DISABLED_FLAG="/var/lib/versa-agi/lifeline.disabled"

# ─── Logging ─────────────────────────────────────────
log() {
  local msg="[$(date '+%Y-%m-%dT%H:%M:%S%z')] [SENTINEL] $*"
  echo "${msg}" >> "${LOG_FILE}"
  echo "${msg}"
}

# ─── Dependency Check ────────────────────────────────
if ! command -v inotifywait &>/dev/null; then
  log "FATAL: inotifywait not found. Install inotify-tools."
  exit 1
fi

if [ ! -f "${AGENTS_DB}" ]; then
  log "FATAL: registry.db not found at ${AGENTS_DB}. Run setup.sh first."
  exit 1
fi

if [ ! -f "${LIFELINE_SCRIPT}" ]; then
  log "FATAL: lifeline.sh not found at ${LIFELINE_SCRIPT}"
  exit 1
fi

# ─── Build Watch List ────────────────────────────────
# Read active agents from registry.db and collect files to watch
WATCH_PATHS=()
AGENT_NAMES=()
AGENT_USERS=()
AGENT_WORKSPACES=()

AGENT_DATA=$(agictl agent get-active || true)

AGENT_COUNT=0
while IFS='|' read -r a_name a_user a_path _rest; do
  [ -z "${a_name}" ] && continue
  AGENT_NAMES+=("${a_name}")
  AGENT_USERS+=("${a_user}")
  AGENT_WORKSPACES+=("${a_path}")
  AGENT_COUNT=$(( AGENT_COUNT + 1 ))
  log "Registered agent: ${a_name} (user: ${a_user}, workspace: ${a_path})"
done <<< "${AGENT_DATA}"

# Hardcode the V3 global unified databases
WATCH_PATHS=()
for f in "/var/lib/versa-agi/messages.db" "/var/lib/versa-agi/coa/tasks.db"; do
  if [ -f "${f}" ]; then
    WATCH_PATHS+=("${f}")
  else
    log "WARN: Watch target not found (will retry on restart): ${f}"
  fi
done

if [ ${#WATCH_PATHS[@]} -eq 0 ]; then
  log "FATAL: No watchable files found. Are agents registered and workspaces initialized?"
  exit 1
fi

log "Watching ${#WATCH_PATHS[@]} file(s) across ${AGENT_COUNT} agent(s)"

# ─── Pre-Check: Should We Trigger? ───────────────────
# Returns 0 (true) if safe to trigger, 1 (false) if skip
should_trigger() {
  local agent_name="$1"
  local agent_user="$2"

  # 1. Debounce — skip if triggered too recently
  local debounce_file="/tmp/versa_agi_sentinel_${agent_name}.debounce"
  if [ -f "${debounce_file}" ]; then
    local last_trigger
    last_trigger=$(cat "${debounce_file}" 2>/dev/null || echo "0")
    local now_epoch
    now_epoch=$(date +%s)
    local elapsed=$(( now_epoch - last_trigger ))
    if [ "${elapsed}" -lt "${DEBOUNCE_SECONDS}" ]; then
      return 1
    fi
  fi

  # 2. CRON Proximity Guard — skip if within 15 seconds of CRON :00 mark
  local current_sec
  current_sec=$(date +%S)
  current_sec=$((10#$current_sec))
  if [ "${current_sec}" -ge 45 ] || [ "${current_sec}" -le 15 ]; then
    log "Skipped trigger: CRON proximity (:$(printf "%02d" "${current_sec}"))"
    return 1
  fi

  # 3. Lock file — skip if lifeline already holds the lock
  local lockfile="/tmp/versa_agi_${agent_name}.lock"
  if [ -f "${lockfile}" ]; then
    if ! flock -n "${lockfile}" true 2>/dev/null; then
      return 1
    fi
  fi

  # 3. Process check — skip if harness is already running for this user
  if pgrep -u "${agent_user}" -f "harness.agent_harness" > /dev/null 2>&1; then
    return 1
  fi

  return 0
}

# ─── Determine Agent from File Path ──────────────────
resolve_agent() {
  local changed_file="$1"

  # 1. Global Databases trigger a system-wide cascade
  if [[ "${changed_file}" == "/var/lib/versa-agi/messages.db" ]] || [[ "${changed_file}" == "/var/lib/versa-agi/coa/tasks.db" ]]; then
    echo "system|watchdog"
    return 0
  fi

  # 2. Agent Workspace Files trigger directly
  for (( i=0; i<AGENT_COUNT; i++ )); do
    local name="${AGENT_NAMES[$i]}"
    local path="${AGENT_WORKSPACES[$i]}"
    local user="${AGENT_USERS[$i]}"

    if [[ "${changed_file}" == "${path}/"* ]]; then
      echo "${name}|${user}"
      return 0
    fi
  done

  return 1
}

# ─── Signal Handling ─────────────────────────────────
SHUTTING_DOWN=0
cleanup() {
  [ "${SHUTTING_DOWN}" -eq 1 ] && return
  SHUTTING_DOWN=1
  log "Sentinel shutting down (signal received)"
  # Kill all child processes (inotifywait)
  kill 0 2>/dev/null || true
  exit 0
}

trap cleanup SIGTERM SIGINT SIGHUP

# ─── Main Watch Loop ────────────────────────────────
log "Sentinel started — PID $$"

run_watcher() {
  inotifywait -m -e modify,create --format '%w%f' "${WATCH_PATHS[@]}" 2>/dev/null
}

run_watcher | while read -r changed_file; do
  # Resolve which agent this file belongs to
  agent_info=$(resolve_agent "${changed_file}" 2>/dev/null || true)
  if [ -z "${agent_info}" ]; then
    continue
  fi

  agent_name="${agent_info%%|*}"
  agent_user="${agent_info##*|}"

  # Pre-checks: debounce, lock, process
  if ! should_trigger "${agent_name}" "${agent_user}"; then
    continue
  fi

  # Record trigger time for debounce
  date +%s > "/tmp/versa_agi_sentinel_${agent_name}.debounce"

  log "TRIGGER: ${agent_name} — file changed: $(basename "${changed_file}")"

  # Honor Lifeline hard OFF (agitop LIFELINE toggle) — do not invoke
  if [ -f "${LIFELINE_DISABLED_FLAG}" ]; then
    log "SKIP: Lifeline disabled (${LIFELINE_DISABLED_FLAG})"
    continue
  fi

  # Invoke Lifeline in background with a 10-second buffer (it handles all spawn logic)
  (sleep 10 && "${LIFELINE_SCRIPT}") &

done

# If we get here, the watcher process exited — system/launchd will restart us
log "File watcher exited — sentinel will restart via system manager"
exit 1
